name: Generate terraform docs
on:
  push:
    paths:
      - '**/*.tf'


jobs:
  docs:
    runs-on: ubuntu-latest
          
    permissions:
        contents: write
        
    steps:
    - uses: actions/checkout@v4

    - name: Render terraform docs and push changes
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"